### ISSUE TITLE
Failed to decode uops.info data

### ISSUE THREAD

**Issue by hghwng** [zwegner/x86-info-term#4]
I guess the data from uops.info has changed. Any idea?

```
Traceback (most recent call last):
  File "x86_info_term.py", line 1308, in <module>
    main()
  File "x86_info_term.py", line 1291, in main
    args, cache = get_cache()
  File "x86_info_term.py", line 1288, in get_cache
    return args, get_info(args)
  File "x86_info_term.py", line 1242, in get_info
    [version, data] = dataset.parse_fn(dataset.full_path)
  File "x86_info_term.py", line 390, in parse_uops_info
    tp = meas.attrib['TP']
KeyError: 'TP'
```

**Comment by zwegner** [comment]
Thanks for the report! Fixed it.

Yeah, the uops.info data changed a bit, adding more throughput data. I went with using the 'TP_unrolled' throughput if the plain 'TP' isn't available.

**Comment by hghwng** [comment]
@zwegner Big thanks for the fix😄 This little utility saved me many hours when exploring SIMD programming!

**Comment by zwegner** [comment]
No problem! And that's great to hear, I use it all the time myself, and other people using it is a nice bonus!
