### ISSUE TITLE
Unnatural behavior for the backspace key

### ISSUE THREAD

**Issue by jaja360** [zwegner/x86-info-term#7]
In the readme, it says: `most normal keys, arrow keys, delete/backspace, etc.: edit the filter with usual key meanings`.

Therefore, I would expect the `backspace` key to have the usual meaning (delete 1 character left of cursor).
Currently, the `backspace` key send the cursor back to the beginning of line.

**Comment by zwegner** [comment]
Thanks for the report! On my machine, backspace returns ASCII DEL (0x7F), but apparently this isn't portable (see https://stackoverflow.com/a/54303430). I had Ctrl-H (which is the same as ASCII backspace 0x08) mapped to home, which was kind of nice, but that isn't worth it if Ctrl-H/backspace can't be reliably distinguished. So I removed that and backspace should work normally now.
